<?php

/* custom routes generated by CRUD */




Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('infrastructures', ['as'=> 'infrastructures.index', 'uses' => 'InfrastructureController@index']);
Route::post('infrastructures', ['as'=> 'infrastructures.store', 'uses' => 'InfrastructureController@store']);
Route::get('infrastructures/create', ['as'=> 'infrastructures.create', 'uses' => 'InfrastructureController@create']);
Route::put('infrastructures/{infrastructures}', ['as'=> 'infrastructures.update', 'uses' => 'InfrastructureController@update']);
Route::patch('infrastructures/{infrastructures}', ['as'=> 'infrastructures.update', 'uses' => 'InfrastructureController@update']);
Route::get('infrastructures/{id}/delete', array('as' => 'infrastructures.delete', 'uses' => 'InfrastructureController@getDelete'));
Route::get('infrastructures/{id}/confirm-delete', array('as' => 'infrastructures.confirm-delete', 'uses' => 'InfrastructureController@getModalDelete'));
Route::get('infrastructures/{infrastructures}', ['as'=> 'infrastructures.show', 'uses' => 'InfrastructureController@show']);
Route::get('infrastructures/{infrastructures}/edit', ['as'=> 'infrastructures.edit', 'uses' => 'InfrastructureController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('providers', ['as'=> 'providers.index', 'uses' => 'ProviderController@index']);
Route::post('providers', ['as'=> 'providers.store', 'uses' => 'ProviderController@store']);
Route::get('providers/create', ['as'=> 'providers.create', 'uses' => 'ProviderController@create']);
Route::put('providers/{providers}', ['as'=> 'providers.update', 'uses' => 'ProviderController@update']);
Route::patch('providers/{providers}', ['as'=> 'providers.update', 'uses' => 'ProviderController@update']);
Route::get('providers/{id}/delete', array('as' => 'providers.delete', 'uses' => 'ProviderController@getDelete'));
Route::get('providers/{id}/confirm-delete', array('as' => 'providers.confirm-delete', 'uses' => 'ProviderController@getModalDelete'));
Route::get('providers/{providers}', ['as'=> 'providers.show', 'uses' => 'ProviderController@show']);
Route::get('providers/{providers}/edit', ['as'=> 'providers.edit', 'uses' => 'ProviderController@edit']);

});

Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('projects', ['as'=> 'projects.index', 'uses' => 'ProjectController@index']);
Route::post('projects', ['as'=> 'projects.store', 'uses' => 'ProjectController@store']);
	Route::get('projects/create', ['as'=> 'projects.create', 'uses' => 'ProjectController@create']);
	Route::get('projects/import', ['as'=> 'projects.import', 'uses' => 'ProjectController@import']);
	Route::get('projects/importpreview/{file}', ['as'=> 'projects.importpreview', 'uses' => 'ProjectController@importPreview']);
	Route::post('projects/import/{file}', ['as'=> 'projects.import.store', 'uses' => 'ProjectController@importStore']);
Route::put('projects/{projects}', ['as'=> 'projects.update', 'uses' => 'ProjectController@update']);
Route::patch('projects/{projects}', ['as'=> 'projects.update', 'uses' => 'ProjectController@update']);
Route::get('projects/{id}/delete', array('as' => 'projects.delete', 'uses' => 'ProjectController@getDelete'));
Route::get('projects/{id}/confirm-delete', array('as' => 'projects.confirm-delete', 'uses' => 'ProjectController@getModalDelete'));
Route::get('projects/{projects}', ['as'=> 'projects.show', 'uses' => 'ProjectController@show']);
Route::get('projects/{projects}/edit', ['as'=> 'projects.edit', 'uses' => 'ProjectController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('images', ['as'=> 'images.index', 'uses' => 'ImageController@index']);
Route::post('images', ['as'=> 'images.store', 'uses' => 'ImageController@store']);
Route::get('images/create', ['as'=> 'images.create', 'uses' => 'ImageController@create']);
Route::put('images/{images}', ['as'=> 'images.update', 'uses' => 'ImageController@update']);
Route::patch('images/{images}', ['as'=> 'images.update', 'uses' => 'ImageController@update']);
Route::get('images/{id}/delete', array('as' => 'images.delete', 'uses' => 'ImageController@getDelete'));
Route::get('images/{id}/confirm-delete', array('as' => 'images.confirm-delete', 'uses' => 'ImageController@getModalDelete'));
Route::get('images/{images}', ['as'=> 'images.show', 'uses' => 'ImageController@show']);
Route::get('images/{images}/edit', ['as'=> 'images.edit', 'uses' => 'ImageController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('news', ['as'=> 'news.index', 'uses' => 'NewsController@index']);
Route::post('news', ['as'=> 'news.store', 'uses' => 'NewsController@store']);
Route::get('news/create', ['as'=> 'news.create', 'uses' => 'NewsController@create']);
Route::put('news/{news}', ['as'=> 'news.update', 'uses' => 'NewsController@update']);
Route::patch('news/{news}', ['as'=> 'news.update', 'uses' => 'NewsController@update']);
Route::get('news/{id}/delete', array('as' => 'news.delete', 'uses' => 'NewsController@getDelete'));
Route::get('news/{id}/confirm-delete', array('as' => 'news.confirm-delete', 'uses' => 'NewsController@getModalDelete'));
Route::get('news/{news}', ['as'=> 'news.show', 'uses' => 'NewsController@show']);
Route::get('news/{news}/edit', ['as'=> 'news.edit', 'uses' => 'NewsController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('beneficiaries', ['as'=> 'beneficiaries.index', 'uses' => 'BeneficiaryController@index']);
Route::post('beneficiaries', ['as'=> 'beneficiaries.store', 'uses' => 'BeneficiaryController@store']);
Route::get('beneficiaries/create', ['as'=> 'beneficiaries.create', 'uses' => 'BeneficiaryController@create']);
Route::put('beneficiaries/{beneficiaries}', ['as'=> 'beneficiaries.update', 'uses' => 'BeneficiaryController@update']);
Route::patch('beneficiaries/{beneficiaries}', ['as'=> 'beneficiaries.update', 'uses' => 'BeneficiaryController@update']);
Route::get('beneficiaries/{id}/delete', array('as' => 'beneficiaries.delete', 'uses' => 'BeneficiaryController@getDelete'));
Route::get('beneficiaries/{id}/confirm-delete', array('as' => 'beneficiaries.confirm-delete', 'uses' => 'BeneficiaryController@getModalDelete'));
Route::get('beneficiaries/{beneficiaries}', ['as'=> 'beneficiaries.show', 'uses' => 'BeneficiaryController@show']);
Route::get('beneficiaries/{beneficiaries}/edit', ['as'=> 'beneficiaries.edit', 'uses' => 'BeneficiaryController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('contacts', ['as'=> 'contacts.index', 'uses' => 'ContactController@index']);
Route::post('contacts', ['as'=> 'contacts.store', 'uses' => 'ContactController@store']);
Route::get('contacts/create', ['as'=> 'contacts.create', 'uses' => 'ContactController@create']);
Route::put('contacts/{contacts}', ['as'=> 'contacts.update', 'uses' => 'ContactController@update']);
Route::patch('contacts/{contacts}', ['as'=> 'contacts.update', 'uses' => 'ContactController@update']);
Route::get('contacts/{id}/delete', array('as' => 'contacts.delete', 'uses' => 'ContactController@getDelete'));
Route::get('contacts/{id}/confirm-delete', array('as' => 'contacts.confirm-delete', 'uses' => 'ContactController@getModalDelete'));
Route::get('contacts/{contacts}', ['as'=> 'contacts.show', 'uses' => 'ContactController@show']);
Route::get('contacts/{contacts}/edit', ['as'=> 'contacts.edit', 'uses' => 'ContactController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('verticals', ['as'=> 'verticals.index', 'uses' => 'VerticalController@index']);
Route::post('verticals', ['as'=> 'verticals.store', 'uses' => 'VerticalController@store']);
Route::get('verticals/create', ['as'=> 'verticals.create', 'uses' => 'VerticalController@create']);
Route::put('verticals/{verticals}', ['as'=> 'verticals.update', 'uses' => 'VerticalController@update']);
Route::patch('verticals/{verticals}', ['as'=> 'verticals.update', 'uses' => 'VerticalController@update']);
Route::get('verticals/{id}/delete', array('as' => 'verticals.delete', 'uses' => 'VerticalController@getDelete'));
Route::get('verticals/{id}/confirm-delete', array('as' => 'verticals.confirm-delete', 'uses' => 'VerticalController@getModalDelete'));
Route::get('verticals/{verticals}', ['as'=> 'verticals.show', 'uses' => 'VerticalController@show']);
Route::get('verticals/{verticals}/edit', ['as'=> 'verticals.edit', 'uses' => 'VerticalController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('locations', ['as'=> 'locations.index', 'uses' => 'LocationController@index']);
Route::post('locations', ['as'=> 'locations.store', 'uses' => 'LocationController@store']);
Route::get('locations/create', ['as'=> 'locations.create', 'uses' => 'LocationController@create']);
Route::put('locations/{locations}', ['as'=> 'locations.update', 'uses' => 'LocationController@update']);
Route::patch('locations/{locations}', ['as'=> 'locations.update', 'uses' => 'LocationController@update']);
Route::get('locations/{id}/delete', array('as' => 'locations.delete', 'uses' => 'LocationController@getDelete'));
Route::get('locations/{id}/confirm-delete', array('as' => 'locations.confirm-delete', 'uses' => 'LocationController@getModalDelete'));
Route::get('locations/{locations}', ['as'=> 'locations.show', 'uses' => 'LocationController@show']);
Route::get('locations/{locations}/edit', ['as'=> 'locations.edit', 'uses' => 'LocationController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('conectivities', ['as'=> 'conectivities.index', 'uses' => 'ConectivityController@index']);
Route::post('conectivities', ['as'=> 'conectivities.store', 'uses' => 'ConectivityController@store']);
Route::get('conectivities/create', ['as'=> 'conectivities.create', 'uses' => 'ConectivityController@create']);
Route::put('conectivities/{conectivities}', ['as'=> 'conectivities.update', 'uses' => 'ConectivityController@update']);
Route::patch('conectivities/{conectivities}', ['as'=> 'conectivities.update', 'uses' => 'ConectivityController@update']);
Route::get('conectivities/{id}/delete', array('as' => 'conectivities.delete', 'uses' => 'ConectivityController@getDelete'));
Route::get('conectivities/{id}/confirm-delete', array('as' => 'conectivities.confirm-delete', 'uses' => 'ConectivityController@getModalDelete'));
Route::get('conectivities/{conectivities}', ['as'=> 'conectivities.show', 'uses' => 'ConectivityController@show']);
Route::get('conectivities/{conectivities}/edit', ['as'=> 'conectivities.edit', 'uses' => 'ConectivityController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoryController@index']);
Route::post('categories', ['as'=> 'categories.store', 'uses' => 'CategoryController@store']);
Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoryController@create']);
Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoryController@getDelete'));
Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoryController@getModalDelete'));
Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoryController@show']);
Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoryController@edit']);

});


Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categoryProjects', ['as'=> 'categoryProjects.index', 'uses' => 'CategoryProjectController@index']);
Route::post('categoryProjects', ['as'=> 'categoryProjects.store', 'uses' => 'CategoryProjectController@store']);
Route::get('categoryProjects/create', ['as'=> 'categoryProjects.create', 'uses' => 'CategoryProjectController@create']);
Route::put('categoryProjects/{categoryProjects}', ['as'=> 'categoryProjects.update', 'uses' => 'CategoryProjectController@update']);
Route::patch('categoryProjects/{categoryProjects}', ['as'=> 'categoryProjects.update', 'uses' => 'CategoryProjectController@update']);
Route::get('categoryProjects/{id}/delete', array('as' => 'categoryProjects.delete', 'uses' => 'CategoryProjectController@getDelete'));
Route::get('categoryProjects/{id}/confirm-delete', array('as' => 'categoryProjects.confirm-delete', 'uses' => 'CategoryProjectController@getModalDelete'));
Route::get('categoryProjects/{categoryProjects}', ['as'=> 'categoryProjects.show', 'uses' => 'CategoryProjectController@show']);
Route::get('categoryProjects/{categoryProjects}/edit', ['as'=> 'categoryProjects.edit', 'uses' => 'CategoryProjectController@edit']);

});
